specVersion: "1.0.0"

name: "flare-subql-starter"
version: "0.0.1"
runner:
  node:
    name: "@subql/node-ethereum"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: "This project can be use as a starting point for developing your new Flare SubQuery project"
repository: "https://github.com/subquery/ethereum-subql-starter"

schema:
  file: "./schema.graphql"

network:
  endpoint: https://flare-api.flare.network/ext/C/rpc
  chainId: "14"

dataSources:
  - kind: flare/Runtime
    startBlock: 2300000
    options:
      # Must be a key of assets
      abi: priceSubmitter
      address: "0x1000000000000000000000000000000000000003"
    assets:
      priceSubmitter:
        file: "priceSubmitter.abi.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleTransaction
          kind: flare/TransactionHandler
          filter:
            ## The function can either be the function fragment or signature
            # function: '0x095ea7b3'
            # function: '0x7ff36ab500000000000000000000000000000000000000000000000000000000'
            function: submitHash(uint256 _epochId, bytes32 _hash)
        - handler: handleLog
          kind: flare/LogHandler
          filter:
            topics:
              ## Follows standard log filters https://docs.ethers.io/v5/concepts/events/
              - HashSubmitted(address indexed submitter, uint256 indexed epochId, bytes32 hash, uint256 timestamp)
